// Generated by gencpp from file uwb_publisher/AddTwoInts.msg
// DO NOT EDIT!


#ifndef UWB_PUBLISHER_MESSAGE_ADDTWOINTS_H
#define UWB_PUBLISHER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <uwb_publisher/AddTwoIntsRequest.h>
#include <uwb_publisher/AddTwoIntsResponse.h>


namespace uwb_publisher
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace uwb_publisher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uwb_publisher::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::uwb_publisher::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::uwb_publisher::AddTwoInts > {
  static const char* value()
  {
    return "uwb_publisher/AddTwoInts";
  }

  static const char* value(const ::uwb_publisher::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::uwb_publisher::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::uwb_publisher::AddTwoInts > 
template<>
struct MD5Sum< ::uwb_publisher::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uwb_publisher::AddTwoInts >::value();
  }
  static const char* value(const ::uwb_publisher::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uwb_publisher::AddTwoIntsRequest> should match 
// service_traits::DataType< ::uwb_publisher::AddTwoInts > 
template<>
struct DataType< ::uwb_publisher::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::uwb_publisher::AddTwoInts >::value();
  }
  static const char* value(const ::uwb_publisher::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uwb_publisher::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::uwb_publisher::AddTwoInts > 
template<>
struct MD5Sum< ::uwb_publisher::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uwb_publisher::AddTwoInts >::value();
  }
  static const char* value(const ::uwb_publisher::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uwb_publisher::AddTwoIntsResponse> should match 
// service_traits::DataType< ::uwb_publisher::AddTwoInts > 
template<>
struct DataType< ::uwb_publisher::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::uwb_publisher::AddTwoInts >::value();
  }
  static const char* value(const ::uwb_publisher::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UWB_PUBLISHER_MESSAGE_ADDTWOINTS_H
