// Generated by gencpp from file uwb_publisher/distance.msg
// DO NOT EDIT!


#ifndef UWB_PUBLISHER_MESSAGE_DISTANCE_H
#define UWB_PUBLISHER_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwb_publisher
{
template <class ContainerAllocator>
struct distance_
{
  typedef distance_<ContainerAllocator> Type;

  distance_()
    : module()
    , range(0.0)  {
    }
  distance_(const ContainerAllocator& _alloc)
    : module(_alloc)
    , range(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _module_type;
  _module_type module;

   typedef float _range_type;
  _range_type range;




  typedef boost::shared_ptr< ::uwb_publisher::distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_publisher::distance_<ContainerAllocator> const> ConstPtr;

}; // struct distance_

typedef ::uwb_publisher::distance_<std::allocator<void> > distance;

typedef boost::shared_ptr< ::uwb_publisher::distance > distancePtr;
typedef boost::shared_ptr< ::uwb_publisher::distance const> distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_publisher::distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_publisher::distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb_publisher

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'uwb_publisher': ['/home/micke/ExamensarbeteCybercom/catkin_ws/src/uwb_publisher/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb_publisher::distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_publisher::distance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_publisher::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_publisher::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_publisher::distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_publisher::distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_publisher::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f2d3ae4b9285bc707ca0f585f4f7b8";
  }

  static const char* value(const ::uwb_publisher::distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f2d3ae4b9285bcULL;
  static const uint64_t static_value2 = 0x707ca0f585f4f7b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_publisher::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_publisher/distance";
  }

  static const char* value(const ::uwb_publisher::distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_publisher::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string module\n\
float32 range\n\
";
  }

  static const char* value(const ::uwb_publisher::distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_publisher::distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.module);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_publisher::distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_publisher::distance_<ContainerAllocator>& v)
  {
    s << indent << "module: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.module);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_PUBLISHER_MESSAGE_DISTANCE_H
