classdef hq_RobotTaskResult < robotics.ros.Message
    %hq_RobotTaskResult MATLAB implementation of hq_robot_task/hq_RobotTaskResult
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'hq_robot_task/hq_RobotTaskResult' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '2a3ce67db61409507027bbc08434f3e8' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Success
        Description
        Plan
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Description', 'Plan', 'Success'} % List of non-constant message properties
        ROSPropertyList = {'description', 'plan', 'success'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = hq_RobotTaskResult(msg)
            %hq_RobotTaskResult Construct the message object hq_RobotTaskResult
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function success = get.Success(obj)
            %get.Success Get the value for property Success
            success = int32(obj.JavaMessage.getSuccess);
        end
        
        function set.Success(obj, success)
            %set.Success Set the value for property Success
            validateattributes(success, {'numeric'}, {'nonempty', 'scalar'}, 'hq_RobotTaskResult', 'Success');
            
            obj.JavaMessage.setSuccess(success);
        end
        
        function description = get.Description(obj)
            %get.Description Get the value for property Description
            description = char(obj.JavaMessage.getDescription);
        end
        
        function set.Description(obj, description)
            %set.Description Set the value for property Description
            validateattributes(description, {'char'}, {}, 'hq_RobotTaskResult', 'Description');
            
            obj.JavaMessage.setDescription(description);
        end
        
        function plan = get.Plan(obj)
            %get.Plan Get the value for property Plan
            plan = char(obj.JavaMessage.getPlan);
        end
        
        function set.Plan(obj, plan)
            %set.Plan Set the value for property Plan
            validateattributes(plan, {'char'}, {}, 'hq_RobotTaskResult', 'Plan');
            
            obj.JavaMessage.setPlan(plan);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Success = obj.Success;
            cpObj.Description = obj.Description;
            cpObj.Plan = obj.Plan;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Success = strObj.Success;
            obj.Description = strObj.Description;
            obj.Plan = strObj.Plan;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Success = obj.Success;
            strObj.Description = obj.Description;
            strObj.Plan = obj.Plan;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.hq_robot_task.hq_RobotTaskResult.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.hq_robot_task.hq_RobotTaskResult;
            obj.reload(strObj);
        end
    end
end
